# Madison Qualley
## wk 10, 10/27/2020
### Pyhton numpy intro

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
arr = np.array ([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array((1,2,3,4,5,6))

In [7]:
arr1

array([1, 2, 3, 4, 5, 6])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
# 0-D Arrays
arr2 = np.array(50)

In [10]:
arr2

array(50)

In [11]:
print(arr2)

50


In [12]:
#1 - D array
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [13]:
#2-D array - matrix

arr4= np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [14]:
#3-D array

arr5 = np.array( [ [1,2,3],[4,5,6],[11,22,33],[44,55,66] ])
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [15]:
print(arr2)

50


In [16]:
print(arr2.ndim)

0


In [17]:
print(arr3.ndim)

1


In [18]:
print(arr4.ndim)

2


In [19]:
print(arr5.ndim)

2


In [20]:
#Array Indexig
#Access 1-d
print(arr3)

[1 2 3 4 5 6]


In [21]:
print(arr3[1])

2


In [22]:
print(arr3[-1])

6


In [23]:
print(arr3[0] + arr3[3])

5


In [24]:
#2-D array
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [25]:
print(arr4[0,1])

2


In [26]:
print(arr4[1,-1])

66


In [27]:
print(arr4[1,3])

44


In [28]:
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]


In [29]:
print(arr5[0,1])

2


In [30]:
print(arr5[1,1])

5


In [31]:
 marr = np.array([1,2,3,4,5], ndmin = 5)

In [32]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [33]:
marr.ndim

5

In [34]:
print(arr4[0,-1])

6


In [35]:
#slicing np arrays
#[start:end]
#[start:end:step]
#[:end] start is 0
#[start: ] end will be the length of the array


In [36]:
print(arr3)

[1 2 3 4 5 6]


In [37]:
arr3

array([1, 2, 3, 4, 5, 6])

In [38]:
print(arr3[1:4])

[2 3 4]


In [39]:
print(arr3[3:])

[4 5 6]


In [40]:
#slice elements from the beginning to index 3
print(arr3[:3])

[1 2 3]


In [41]:
print(arr3)

[1 2 3 4 5 6]


In [42]:
#slice from index 3 to end index 1 from the end of the array
print(arr3[-3:-1])

[4 5]


In [43]:
print(arr3[1:5:2])

[2 4]


In [44]:
print(arr3[1:5:1])

[2 3 4 5]


In [45]:
print(arr3)

[1 2 3 4 5 6]


In [46]:
print(arr3[1:5:2])

[2 4]


In [47]:
print(arr3[1:5:3])

[2 5]


In [48]:
#return every other element in the entire array
print(arr3[::])

[1 2 3 4 5 6]


In [49]:
#slicing 2-D numpy arrays
print(arr3.ndim)

1


In [50]:
print(arr3)

[1 2 3 4 5 6]


In [51]:
print(arr4.ndim)

2


In [52]:
print(arr4[1,2])

33


In [53]:
print(arr4[1,1:3])

[22 33]


In [54]:
print(arr4[0:2,3])

[ 4 44]


In [55]:
print(arr4[:,3])

[ 4 44]


In [56]:
print(arr4[:,1:3])

[[ 2  3]
 [22 33]]
