# Madison Qualley
## Week 11, 11/05/2020
### Python NumPy Universal Functions

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z 

[12, 14, 16, 18, 20, 22, 24, 26]

In [2]:
#zip

fname = ("Alice","Bob","Christy")
lname = ("Charlie","Clark","Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([ 0.03812177,  0.68575626,  0.49179983,  0.29467319, -0.55814179,
       -1.2044573 ,  0.18946891, -0.72743802,  0.1090362 ,  0.56636251])

In [9]:
arr2 = np.random.randn(10)

arr2

array([ 1.47375936, -2.02840273, -0.11252578, -0.3437565 , -0.09685514,
        0.40378504,  1.43499144,  0.3636599 , -1.01144332,  1.07126339])

In [10]:
np.add(arr1,arr2)

array([ 1.51188114, -1.34264647,  0.37927405, -0.0490833 , -0.65499693,
       -0.80067225,  1.62446035, -0.36377812, -0.90240712,  1.6376259 ])

In [11]:
np.maximum(arr1,arr2)

array([ 1.47375936,  0.68575626,  0.49179983,  0.29467319, -0.09685514,
        0.40378504,  1.43499144,  0.3636599 ,  0.1090362 ,  1.07126339])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
print(np.where(arr < 4, -1,-2))

[[-1 -1 -1]
 [-1 -2 -2]
 [-2 -2 -2]]


In [15]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [18]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [19]:
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [20]:
arr_b = np.array ((True,False,True,False,False))

arr_b.any()

True

In [21]:
arr_b.all()

False

In [22]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [24]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [25]:
#statistical measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
arr.sum()

45

In [28]:
arr.sum(0)

array([12, 15, 18])

In [29]:
arr.sum(1)

array([ 6, 15, 24])

In [30]:
print(arr)
np.sum(arr, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [32]:
arr.mean()

5.0

In [33]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [34]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [35]:
np.mean(arr,axis = 0)

array([4., 5., 6.])

In [36]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [37]:
arr.var()

6.666666666666667

In [38]:
arr.std()

2.581988897471611

In [39]:
arr = np.array([3,6,7,8,4,2,3,6,8,9,0,1,2,4,4,3,])

arr.sort()

arr

array([0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 6, 6, 7, 8, 8, 9])

In [40]:
#identify array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a = np.arange(4).reshape((2,2))

a

array([[0, 1],
       [2, 3]])

In [43]:
a

array([[0, 1],
       [2, 3]])

In [44]:
a *1

array([[0, 1],
       [2, 3]])

In [46]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))

a * 1

[[1. 0.]
 [0. 1.]]


array([[0, 1],
       [2, 3]])

In [47]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [48]:
m * 1

matrix([[1, 2],
        [3, 4]])

In [49]:
#Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print('----------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
----------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [50]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [51]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [53]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [54]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [55]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [56]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [57]:
np.random.random((4,4))

array([[0.29344929, 0.05343008, 0.32900115, 0.48592812],
       [0.65925819, 0.32577317, 0.07105412, 0.56801606],
       [0.23530409, 0.66091053, 0.12354629, 0.16384001],
       [0.63355736, 0.36875218, 0.41936942, 0.59076842]])

In [58]:
from numpy.random import random
random((4,4))

array([[0.40552259, 0.90942106, 0.56700773, 0.45228791],
       [0.12098816, 0.14811808, 0.03545062, 0.14855857],
       [0.67166324, 0.2505834 , 0.55151738, 0.30133169],
       [0.57465595, 0.59523224, 0.54576232, 0.89246732]])

In [59]:
from numpy.random import randn
randn(5,5)

array([[-1.00394984,  0.1707716 , -0.32542854,  0.12317342, -1.45173772],
       [ 0.35327189, -1.34251804,  1.41943919, -1.42490011, -0.16496073],
       [ 0.50989888,  0.20671365, -1.06035805, -0.4407053 , -0.26539387],
       [-0.75395496, -0.01839613,  1.70927915,  0.78719449,  0.99912307],
       [ 1.00595069, -0.33246973,  1.18445544,  0.52844974,  0.9406108 ]])

In [60]:
randn(5)

array([ 0.18893907, -0.49794261, -1.68480334, -0.82374581, -0.35405747])

In [61]:
np.random.randint(10,50)

46

In [62]:
website = "https://numpy.org/doc/stable/reference/ufuncs.html"

import webbrowser
webbrowser.open(website)

True

In [63]:
import pandas as pd